config/routes.rb
Rails.application.routes.draw do
  resources :gce_zones
  resources :gce_regions
  get 'welcome/about'
  get 'welcome/index'
  get 'welcome/license'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  resources :just_routes

  resources :gce_regions do
    resources :gce_zones
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gce_region.rb
class GceRegion < ApplicationRecord
  # attr_accessible :address, :name, :description
  has_many :gce_zones


  validates :name,  :presence => true, format: { with: /\A[a-z]+-[a-z]+\d+\z/, 
    	message: "Use following format: $CONTINENT-$POSITION$DIGITS (all lowercase), e.g. 'antarctica-west42'"}
  validates_uniqueness_of :name
  #validates :title, :presence => true, :length => { :minimum => 5 }
  #validates :default_zones, presence: true, 
	#    create_table :gce_regions do |t|
    #  t.string :name
    #  t.string :address
    #  t.text :description
    #  t.boolean :is_active, default: TRUE
    #  also added default_zones :string
  def continent
    name.split('-')[0]
  end

  # syntactic sugar but soooo rubyish!
  def is_active?
  	is_active
  end

  def to_s
  	return_value = name
  	return_value += " (INACTIVE)" unless is_active?
  	return_value
  end

  def zones
  	gce_zones
  end

  def validate
    gce.zones.each {|z| z.validate }

  end

  def autocreate_child_zones
  	zones = self.default_zones.split(",").map{|x| x.strip } # ['a','b','c']
  	zones.each do |z| 
  	  return_value = GceZone.create_by_region_and_suffix(self, z) # .save
  	  print "Creating zone #{z} for Region #{self}... #{return_value}\n"
	end
  end

#    $ rails generate model Comment commenter:string body:text post:references
end

app/models/gce_zone.rb
class GceZone < ApplicationRecord
  #belongs_to :GceRegion
  belongs_to :gce_region

  validates :name,  :presence => true, format: { with: /\A[a-z]+-[a-z]+\d+-[a-z]\z/, 
    	message: "Use following format: $CONTINENT-$POSITION$DIGITS-$ALPHA (all lowercase), e.g. 'antarctica-west42-f'"}
  validates_uniqueness_of :name

  def to_s
  	name
  end

  def validate
    z = self.name
    r = self.gce_region.name
    # ASSERT z starts with r
    raise "Wrong name! R(#{r}) <=> Z(#{z})" unless z.start_with?(r)
  end

  def self.create_by_region_and_suffix(region, suffix)
    # Example: Region("antarctica-west42"), 'a' => "antarctica-west42-a" zne
    # TODO(ricc): validate region is a GceRegion
    # TODO(ricc): validate suffix is a /[a-z]/
    #assert_match(/[a-z]/, suffix)
    #assert_instance_of GceRegion, region
    
    GceZone.create(name: region.name + "-" + suffix, gce_region_id: region.id, is_active: region.is_active)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gce_regions_controller.rb
class GceRegionsController < ApplicationController
  before_action :set_gce_region, only: [:show, :edit, :update, :destroy]

  # GET /gce_regions
  # GET /gce_regions.json
  def index
    @gce_regions = GceRegion.all
  end

  # GET /gce_regions/1
  # GET /gce_regions/1.json
  def show
  end

  # GET /gce_regions/new
  def new
    @gce_region = GceRegion.new
  end

  # GET /gce_regions/1/edit
  def edit
  end

  # POST /gce_regions
  # POST /gce_regions.json
  def create
    @gce_region = GceRegion.new(gce_region_params)

    respond_to do |format|
      if @gce_region.save
        format.html { redirect_to @gce_region, notice: 'Gce region was successfully created.' }
        format.json { render :show, status: :created, location: @gce_region }
      else
        format.html { render :new }
        format.json { render json: @gce_region.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gce_regions/1
  # PATCH/PUT /gce_regions/1.json
  def update
    respond_to do |format|
      if @gce_region.update(gce_region_params)
        format.html { redirect_to @gce_region, notice: 'Gce region was successfully updated.' }
        format.json { render :show, status: :ok, location: @gce_region }
      else
        format.html { render :edit }
        format.json { render json: @gce_region.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gce_regions/1
  # DELETE /gce_regions/1.json
  def destroy
    @gce_region.destroy
    respond_to do |format|
      format.html { redirect_to gce_regions_url, notice: 'Gce region was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gce_region
      @gce_region = GceRegion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gce_region_params
      params.require(:gce_region).permit(:name, :address, :description, :default_zones, :is_active)
    end
end

app/controllers/gce_zones_controller.rb
class GceZonesController < ApplicationController
  before_action :set_gce_zone, only: [:show, :edit, :update, :destroy]

  # GET /gce_zones
  # GET /gce_zones.json
  def index
    @gce_zones = GceZone.all
  end

  # GET /gce_zones/1
  # GET /gce_zones/1.json
  def show
  end

  # GET /gce_zones/new
  def new
    @gce_zone = GceZone.new
  end

  # GET /gce_zones/1/edit
  def edit
  end

  # POST /gce_zones
  # POST /gce_zones.json
  def create
    #@gce_region = GceRegion.find(params[:gce_region_id])
    #@gce_zone = @gce_region.gce_zones.create(params[:gce_zone])
    #redirect_to region_path(@region)

    @gce_zone = GceZone.new(gce_zone_params)

    respond_to do |format|
      if @gce_zone.save
        format.html { redirect_to @gce_zone, notice: 'Gce Zone was successfully created.' }
        format.json { render :show, status: :created, location: @gce_zone }
      else
        format.html { render :new }
        format.json { render json: @gce_zone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gce_zones/1
  # PATCH/PUT /gce_zones/1.json
  def update
    respond_to do |format|
      if @gce_zone.update(gce_zone_params)
        format.html { redirect_to @gce_zone, notice: 'Gce zone was successfully updated.' }
        format.json { render :show, status: :ok, location: @gce_zone }
      else
        format.html { render :edit }
        format.json { render json: @gce_zone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gce_zones/1
  # DELETE /gce_zones/1.json
  def destroy
    @gce_zone.destroy
    respond_to do |format|
      format.html { redirect_to gce_zones_url, notice: 'Gce zone was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gce_zone
      @gce_zone = GceZone.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gce_zone_params
      params.require(:gce_zone).permit(:name, :is_active, :GceRegion_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  #layout 'application' # default

  def index
  end

  def about
  end
  def license
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gce_regions_helper.rb
module GceRegionsHelper
end

app/helpers/gce_zones_helper.rb
module GceZonesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/gce_regions/_form.html.erb
<%= form_with(model: gce_region, local: true) do |form| %>
  <% if gce_region.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gce_region.errors.count, "error") %> prohibited this gce_region from being saved:</h2>

      <ul>
      <% gce_region.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :default_zones %>
    <%= form.text_field :default_zones %>
  </div>

  <div class="field">
    <%= form.label :is_active %>
    <%= form.text_field :is_active %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/gce_regions/edit.html.erb
<h1>Editing Gce Region</h1>

<%= render 'form', gce_region: @gce_region %>

<%= link_to 'Show', @gce_region %> |
<%= link_to 'Back', gce_regions_path %>

app/views/gce_regions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gce Regions</h1>

Note CPOUs and Resoureces better pertain to ZONES, not regions. They should be refactored there when you have some time.
Maybe move from TSV to a gcloud zones list and populate from API :)

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Zones</th>
      <th>Dflt Zones</th>
      <th>MachineTypes</th>
      <th>CPUs</th>
      <th>Resources</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gce_regions.each do |gce_region| %>
      <tr>
        <td><%= link_to gce_region.name,gce_region %></td>
        <td><%= gce_region.address %></td>
        <td><% gce_region.gce_zones.each do |z| %>
            <%= link_to z,z %>
        <% end %>
        </td>
        <td><%= gce_region.default_zones %></td>
        <td><%= gce_region.machine_types %></td>
        <td><%= gce_region.cpus %></td>
        <td><%= gce_region.resources %></td>
        <td><%= link_to 'Edit', edit_gce_region_path(gce_region) %></td>
        <td><%= link_to 'Destroy', gce_region, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gce Region', new_gce_region_path %>

app/views/gce_regions/new.html.erb
<h1>New Gce Region</h1>

<%= render 'form', gce_region: @gce_region %>

<%= link_to 'Back', gce_regions_path %>

app/views/gce_regions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @gce_region.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @gce_region.address %>
</p>

<p>
  <strong>Description:</strong>
  <%= @gce_region.description %>
</p>

<p>
  <strong>Default Zones:</strong>
  <%= @gce_region.default_zones %>
</p>

<p>
  <strong>Is active:</strong>
  <%= @gce_region.is_active %>
</p>

<h2>Zones under this region</h2>
  <% @gce_region.zones.each do |zone| %>
    <p>
      <%= link_to zone, zone %>      
    </p>
  <% end %>

<h2>Add a Zone under this region</h2>

  <%= form_for([@gce_region, @gce_region.gce_zones.build]) do |f| %>
    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>


<%= link_to 'Edit', edit_gce_region_path(@gce_region) %> |
<%= link_to 'Back', gce_regions_path %>

app/views/gce_zones/_form.html.erb
<%= form_with(model: gce_zone, local: true) do |form| %>
  <% if gce_zone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gce_zone.errors.count, "error") %> prohibited this gce_zone from being saved:</h2>

      <ul>
      <% gce_zone.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :is_active %>
    <%= form.text_field :is_active %>
  </div>

  <div class="field">
    <%= form.label :gce_region_id %>
    <%= form.text_field :gce_region_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/gce_zones/edit.html.erb
<h1>Editing Gce Zone</h1>

<%= render 'form', gce_zone: @gce_zone %>

<%= link_to 'Show', @gce_zone %> |
<%= link_to 'Back', gce_zones_path %>

app/views/gce_zones/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gce Zones</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Is active</th>
      <th>Gceregion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gce_zones.each do |gce_zone| %>
      <tr>
        <td><%= gce_zone.name %></td>
        <td><%= gce_zone.is_active %></td>
        <td><%= link_to gce_zone.gce_region, gce_zone.gce_region %></td>
        <td><%= link_to 'Show', gce_zone %></td>
        <td><%= link_to 'Edit', edit_gce_zone_path(gce_zone) %></td>
        <td><%= link_to 'Destroy', gce_zone, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gce Zone', new_gce_zone_path %>

app/views/gce_zones/new.html.erb
<h1>New Gce Zone</h1>

<%= render 'form', gce_zone: @gce_zone %>

<%= link_to 'Back', gce_zones_path %>

app/views/gce_zones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @gce_zone.name %>
</p>

<p>
  <strong>Is active:</strong>
  <%= @gce_zone.is_active %>
</p>

<p>
  <strong>GCE Region:</strong>
  <%= link_to @gce_zone.gce_region, @gce_zone.gce_region %> 
</p>

<%= link_to 'Edit', edit_gce_zone_path(@gce_zone) %> |
<%= link_to 'Back', gce_zones_path %>

app/views/layouts/_footer.html.erb
<hr/>
<div class='footer' align='center'>
  AppName: <b><%=$APP[:name] %></b> v.<%= $APP[:version] %> , by <a href="https://github.com/palladius/" >Palladius</a>.


</div>

app/views/layouts/_header.html.erb
<div class='header' align='center'>
	[ 
		<a href="/welcome/about">About</a> |
		<a href="/gce_regions/">GCE Regions</a> |
		<a href="/gce_zones/">GCE Zones</a> |
		<a href="/welcome/index">Home</a> |
		<a href="/welcome/license">License</a> 
	]
</div>
<hr/>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoldieRails5Ruby2 (Application Layout)</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render :partial => "layouts/header" %>
    <div class='mainer'>
      <%= yield %>
    </div>
    <%= render :partial => "layouts/footer" %>
  </body>
</html>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

note this doesnt 

<h2>App Info</h2>

Change this data in `config/initializers/riccardo_constants.rb`:

<pre>
<%$APP.each  do |k,v| %>
  <b><%= k %></b>: <%= v %> 
<% end %>	
</pre>

app/views/welcome/index.html.erb
<h1>Welcome</h1>


<p>This is a TEMPLATE app (really? <b><%= $APP[:is_template] %></b>!) which you should take and cut and paste :)</p>

<%= link_to "My GCE Regions", gce_regions_path %>

<h2>History</h2>
<pre>
<%= $APP[:history] %>
</pre>

app/views/welcome/license.html.erb
<h1>License</h1>

<pre>
<%= $APP[:license] %>	
</pre>